import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const galxe = localFont({
  src: "../../public/fonts/galxe.woff2",
  variable: "--font-galxe",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${galxe.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
